### ISSUE TITLE
[어드민] 데이터베이스 접근 로직 테스트 정의

### ISSUE THREAD

**Issue by solpinetree** [solpinetree/study-project-board-admin#6]
이 프로젝트가 DB를 사용할 수 있도록 환경을 구성하고 테스트를 정의한다.

### TODO
---
* [x] db 만들기
* [x] 계정 권한 주기
* [x] IDE 접근 환경 설정 
* [x] repository 코드 작성 
* [x] 관련 테스트 작성

**Comment by solpinetree** [comment]
```mysql
grant all on `admin`.* to 'sol'@'localhost' with grant option;
flush privileges;
```
